FROM nginx:alpine

WORKDIR /app

RUN mkdir ./logs
RUN mkdir ./www

COPY ./app.conf /etc/nginx/conf.d/default.conf
COPY ./www /app/www

RUN chown -R nginx:nginx /app
RUN chmod -R 755 /app

CMD ["nginx", "-g", "daemon off;"]